print(´Hello, World´)
print(´Meu nome é zayon´)
print(´e a minha comida faorita é lasanha´)
print(´Meu hobby é ler livros´)
print(´Meu livro favorito é A Ruína Dourada´)
print(´Trono de Vidro´)
print(´Quero uma receita de bolo´)
print(´Como frita um ovo´)
print(´Quero uma caixa de uva´)
print(´Tô com sono´)